### ISSUE TITLE
Ride days needs to correct for time zone

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-web#34]
>> I agree that the ride should count because of the time difference, etc. But... how can he have 4 days ridden so far when it is January 3rd? Something else seems to be off.
>
> I don't know if I wrote that piece, but I believe the logic is truncating to the date value, which would count as 4 days -- i.e. It isn't calculating a time delta. I think we need to tweak that metric to take the truncated contest dates also into consideration.
>
> Edit: the ride start dates just need to be converted to EST5EDT before the date is truncated.

**Comment by hozn** [comment]
@jrenaut , assigning this over to you as I seem to remember you wrote this piece.  I may be wrong; happy to have a look at it myself if so.  I haven't looked at the code at all, but basically the ride start dates need to be normalized to easter time before we examine the dates.  I think that can all happen in the db; there should be precedent for that.

**Comment by jrenaut** [comment]
So the ride days is pulling a count of dates in the daily_scores view, so there's no timezone to convert there. Does it make sense to do the conversion in the view? 

I'm actually not sure it makes sense to convert at all. The rules are that local time applies, right? So VVill actually does have 5 days when EST riders have 4 because he's most of a day ahead. Contest just ends early for him. This is going to get fun when I'm in Melbourne in February...

**Comment by hozn** [comment]
Hmmm, yeah, I guess I need to give this a little thought.  Maybe it doesn't make sense to change it; we just have to be careful to not use this value to determine "rode all days" when you get an extra "day" at the beginning/end of the competition.

**Comment by hozn** [comment]
Sorry, I should have looked at the code before assigning it to you; sounds like you had nothing to do with this implementation :)

**Comment by jrenaut** [comment]
Ha, no worries, good to have the discussion

**Comment by obscurerichard** [comment]
This is really fixed in version 1.1.8 of https://github.com/freezingsaddles/freezing-web/

See #101, #103, and #104 also.
